/**
 * 全局的所有Action便利
 */

const LOGIN_SUCCESS = 0x1;
const LOGOUT = 0x2;
const ADD_BOOK_COLLECTION = 0x3;
const ADD_MUSIC_COLLECTION = 0x4;
const ADD_FILM_COLLECTION = 0x5;
const REMOVE_BOOK_COLLECTION = 0x6;
const REMOVE_MUSIC_COLLECTION = 0x7;
const REMOVE_FILM_COLLECTION = 0x8;
const INIT_BOOK_COLLECTION = 0x9;
const INIT_MUSIC_COLLECTION = 0x10;
const INIT_FILM_COLLECTION = 0x11;

const Action = {
  LOGIN_SUCCESS,
  LOGOUT,
  ADD_BOOK_COLLECTION,
  ADD_MUSIC_COLLECTION,
  ADD_FILM_COLLECTION,
  REMOVE_BOOK_COLLECTION,
  REMOVE_MUSIC_COLLECTION,
  REMOVE_FILM_COLLECTION,
  INIT_BOOK_COLLECTION,
  INIT_MUSIC_COLLECTION,
  INIT_FILM_COLLECTION,
}

export default Action;